'use client'

import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from 'react';
import { Provider } from 'react-redux';
import { store } from "@/store";


// export const metadata: Metadata = {
//   title: "Modfit | Modest Wears",
//   description: "Generated by create next app",
// };



export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html>
      <body>
        <Provider store={store}>
          {children}
        </Provider>
      </body>
    </html>
  );
}

